// @ts-nocheck
/**
 * =============================================================================
 * BACKEND REFERENCE — Subvendors + office-inside ledger (§BD, Sep 2026)
 * =============================================================================
 *
 * Frontend: /dashboard/subvendors (already built). Replaces localStorage-only
 * vendors + ledger with PostgreSQL.
 *
 * Status: IMPLEMENTED in this repo.
 *   - models/Subvendor.ts, models/SubvendorLedger.ts (+ associations in models/index-quotation.ts)
 *   - database/migrations/20260928120000-create-subvendors-and-ledger.js
 *   - config/sequelizeBootstrap.ts → ensureSubvendorTables() (idempotent at boot)
 *   - utils/subvendorApi.ts → publicSubvendor / publicLedger / roundInr / parsers
 *   - controllers/subvendorController.ts
 *   - routes/adminRoutes.ts (after router.use(authorizeAdmin) → admin JWT only)
 *
 * -----------------------------------------------------------------------------
 * 1) SQL (abridged — source of truth: database/migrations/20260928120000-create-subvendors-and-ledger.js;
 *    profile / amount columns there are NOT NULL with '' / 0 defaults)
 * -----------------------------------------------------------------------------
 *
 *   CREATE TABLE IF NOT EXISTS subvendors (
 *     id           UUID PRIMARY KEY,
 *     kind         VARCHAR(20)  NOT NULL CHECK (kind IN ('office_inside','office_outside')),
 *     dealer_id    VARCHAR(50)  NULL REFERENCES dealers(id) ON DELETE SET NULL,
 *     name         VARCHAR(255) NOT NULL,
 *     contact_name VARCHAR(255), mobile VARCHAR(30), email VARCHAR(255),
 *     city         VARCHAR(120), category VARCHAR(80) DEFAULT 'Other', notes TEXT,
 *     created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 *     updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
 *   );
 *   CREATE UNIQUE INDEX IF NOT EXISTS subvendors_office_inside_dealer_uidx
 *     ON subvendors (dealer_id) WHERE kind = 'office_inside' AND dealer_id IS NOT NULL;
 *
 *   CREATE TABLE IF NOT EXISTS subvendor_ledger (
 *     id              UUID PRIMARY KEY,
 *     quotation_id    VARCHAR(50) NOT NULL UNIQUE REFERENCES quotations(id) ON DELETE CASCADE,
 *     vendor_id       UUID NULL REFERENCES subvendors(id) ON DELETE SET NULL,
 *     loan_amount     NUMERIC(14,2) DEFAULT 0, received_amount NUMERIC(14,2) DEFAULT 0,
 *     remaining       NUMERIC(14,2) DEFAULT 0, proposal        NUMERIC(14,2) DEFAULT 0,
 *     cost_of_site    NUMERIC(14,2) DEFAULT 0, file_charges    NUMERIC(14,2) DEFAULT 0,
 *     pi              NUMERIC(14,2) DEFAULT 0, gst_charges     NUMERIC(14,2) DEFAULT 0,
 *     others          NUMERIC(14,2) DEFAULT 0,
 *     updated_by      VARCHAR(50),
 *     created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 *     updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
 *   );
 *
 *   §BE (migration 20260929120000-add-profit-ratio-to-subvendors.js):
 *   ALTER TABLE subvendors ADD COLUMN IF NOT EXISTS profit_ratio NUMERIC(6, 2) NOT NULL DEFAULT 0;
 *
 *   §BJ (migration 20261005120000-add-file-cost-and-leaser-to-subvendors.js):
 *   ALTER TABLE subvendors
 *     ADD COLUMN IF NOT EXISTS file_cost_per_kw NUMERIC(14,2) NOT NULL DEFAULT 1000,
 *     ADD COLUMN IF NOT EXISTS leaser_paid      NUMERIC(14,2) NOT NULL DEFAULT 0,
 *     ADD COLUMN IF NOT EXISTS leaser_remaining NUMERIC(14,2) NOT NULL DEFAULT 0;
 *
 *   IDs are STRING(50) in this repo for dealers/quotations → FKs are VARCHAR(50).
 *   UUIDs are generated by Sequelize (UUIDV4), so no pgcrypto dependency.
 *
 * -----------------------------------------------------------------------------
 * 2) Endpoints (all /api/admin, admin JWT; non-admin → 403 AUTH_004)
 * -----------------------------------------------------------------------------
 *
 *   GET    /subvendors?kind=office_inside|office_outside
 *          → { success: true, data: { subvendors: Subvendor[] } }   (ordered by name)
 *
 *   POST   /subvendors
 *          body: { kind, dealerId?, name?, contactName?, mobile?, email?, city?, category?, notes?,
 *                  profitRatio?, fileCostPerKw?, leaserPaid?, leaserRemaining? }   (snake_case accepted)
 *          profitRatio (§BE): percent 0–100, two decimals (roundProfitRatio); empty / invalid → 0.
 *          fileCostPerKw (§BJ): whole INR; missing / 0 / invalid → 1000 (roundFileCostPerKw).
 *          leaserPaid / leaserRemaining (§BJ): whole INR, >= 0; POST default 0.
 *          PATCH only writes keys that are sent — omitted keys keep the stored value
 *          (parseSubvendorRateFields).
 *          kW rounding, file charges (round(kW) × fileCostPerKw) and profit amount are FE-only.
 *          → 201 { success: true, data: { subvendor } }
 *
 *   PATCH  /subvendors/:id   (same body, any subset)
 *          → { success: true, data: { subvendor } }
 *
 *   DELETE /subvendors/:id
 *          → { success: true, data: { id, deleted: true } }
 *          Ledger rows are NOT deleted — their vendor_id is set to null.
 *
 *   GET    /subvendors/ledger?vendorId=&search=
 *          vendorId: dealer id (matches subvendors.dealer_id or quotation.dealerId);
 *                    a subvendor UUID is also accepted.
 *          search:   ILIKE on customer first/last name, customer mobile, vendor name, quotation id.
 *          → { success: true, data: { items: Ledger[] } }
 *
 *   PATCH  /subvendors/ledger/:quotationId
 *          body: any subset of { loanAmount, receivedAmount, remaining, proposal, costOfSite,
 *                                fileCharges, pi, gstCharges, others, vendorId? }
 *          Partial upsert by quotation_id. Missing / null keys are NOT written, so existing
 *          columns are never reset. Amounts rounded to whole INR (negatives → 0).
 *          vendor_id = explicit valid vendorId, else the office_inside subvendor whose
 *          dealer_id = quotation.dealerId.
 *          → { success: true, data: { item: Ledger } }
 *
 *   snake_case input aliases accepted: dealer_id, contact_name, loan_amount, received_amount,
 *   cost_of_site, file_charges, gst_charges, vendor_id.
 *
 * -----------------------------------------------------------------------------
 * 3) Validation + error codes  → { success: false, error: { code, message } }
 * -----------------------------------------------------------------------------
 *
 *   VAL_KIND        400  kind missing / not office_inside|office_outside (aliases inside/outside ok)
 *   VAL_DEALER      400  office_inside without dealerId, or dealer does not exist
 *   VAL_NAME        400  office_outside without name
 *   SUBVENDOR_DUP   409  dealer already has an office_inside subvendor
 *   SUBVENDOR_404   404  unknown subvendor id
 *   QUOTATION_404   404  unknown quotation on ledger PATCH
 *   AUTH_004        403  non-admin JWT
 *
 *   office_inside: blank name / contactName / mobile / email / city are filled from the dealer
 *                  (name = company || "firstName lastName"). Typed values are never overwritten.
 *   office_outside: dealerId forced to null.
 *
 * -----------------------------------------------------------------------------
 * 4) Response shapes (camelCase + snake_case echoed)
 * -----------------------------------------------------------------------------
 */

type Subvendor = {
  id: string;
  kind: 'office_inside' | 'office_outside';
  dealerId: string; dealer_id: string;
  name: string;
  contactName: string; contact_name: string;
  mobile: string; email: string; city: string;
  category: string; // default 'Other'
  notes: string;
  profitRatio: number; profit_ratio: number; // §BE, always present (0 when unset)
  fileCostPerKw: number; file_cost_per_kw: number; // §BJ, default 1000
  leaserPaid: number; leaser_paid: number; // §BJ, default 0
  leaserRemaining: number; leaser_remaining: number; // §BJ, default 0
  createdAt: string; created_at: string;
  updatedAt: string; updated_at: string;
};

type Ledger = {
  quotationId: string; quotation_id: string;
  vendorId: string | null; vendor_id: string | null;
  loanAmount: number; loan_amount: number;
  receivedAmount: number; received_amount: number;
  remaining: number;
  proposal: number;
  costOfSite: number; cost_of_site: number;
  fileCharges: number; file_charges: number;
  pi: number;
  gstCharges: number; gst_charges: number;
  others: number;
  updatedAt: string; updated_at: string;
  // GET /subvendors/ledger only:
  dealerId: string | null; dealer_id: string | null;
  vendorName: string | null; vendor_name: string | null;
  customerName: string | null; customer_name: string | null;
  customerMobile: string | null; customer_mobile: string | null;
};

/**
 * -----------------------------------------------------------------------------
 * 5) QA
 * -----------------------------------------------------------------------------
 *   1. Add office inside (pick dealer) → 201, name prefilled; same dealer again → 409 SUBVENDOR_DUP.
 *   2. Add office outside without name → 400 VAL_NAME.
 *   3. Ledger: PATCH { loanAmount: 1000.6 } → 1001; then PATCH { fileCharges: 250 } → loan still 1001.
 *   4. Delete vendor → ledger rows still in GET, vendorId null.
 *   5. Dealer / visitor / account-management (no admin access) → 403.
 *   6. §BE: POST { profitRatio: 12.345 } → 12.35; PATCH { notes } → still 12.35; PATCH { profitRatio: "" } → 0.
 *   7. §BJ: POST without new keys → fileCostPerKw 1000, leaser 0/0. PATCH { leaserPaid: 50000,
 *      leaser_remaining: 20000 } then PATCH { profitRatio: 10 } → leaser values kept.
 *      PATCH { fileCostPerKw: 0 } → 1000.
 */
